# Generated by Django 4.2.1 on 2023-06-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0002_alter_pin_options_remove_pin_about_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
