# Generated by Django 4.2.1 on 2023-06-14 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pin', '0003_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
