# Generated by Django 4.2.1 on 2023-06-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_cover_photo'),
        ('Pin', '0004_pin_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='postedByProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
