# Generated by Django 4.2.1 on 2023-06-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_image_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.FileField(blank=True, default='vover.png', null=True, upload_to='cover_photo_uploads'),
        ),
    ]
