# Generated by Django 4.2.1 on 2023-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.FileField(blank=True, default='cover.png', null=True, upload_to='cover_photo_uploads'),
        ),
    ]
